    #include P18F4550.inc

    config  FOSC = HS		
    config  CPUDIV = OSC1_PLL2
    config  PLLDIV = 1 
    config  PWRT = OFF
    config  BOR = OFF
    config  WDT = OFF
    config  MCLRE = ON
    config  LVP = OFF
    config  ICPRT = OFF
    config  XINST = OFF
    config  DEBUG = OFF
    config  FCMEN = OFF
    config  IESO = OFF
    config  LPT1OSC = OFF
    config  CCP2MX = ON
    config  PBADEN = OFF
    config  USBDIV = 2
    config  VREGEN = OFF
    
    org 0x0000
    BRA START
    org 0x0008
    BRA HISR
    org 0x0018
    RETFIE
    
    MAIN_CTL equ 0x000
    R1 equ 0x001
    DEBOUNCE_FLAG equ 0x002
    
    REG_NOT equ 0x003
    REG_AND equ 0x004
    REG_OR  equ 0x005
    REG_NAND equ 0x006
    REG_XOR equ 0x007
    REG_NOR equ 0x008
    


START:
    
    MOVLW 0x0F
    MOVWF ADCON1, ACCESS
    ; SET COMPARATORS to disable
    MOVLW 0x07
    MOVWF CMCON, ACCESS
    
    ;OUTPUT LEDS
    CLRF TRISA, ACCESS
    CLRF LATA, ACCESS
    
    CLRF TRISB, ACCESS
    CLRF LATB, ACCESS
    
    CLRF TRISD, ACCESS
    CLRF LATD, ACCESS
        
    ;PORT C for GATE SELECTOR
    BSF TRISC, RC0, ACCESS
    BSF TRISC, RC1, ACCESS
    BSF TRISC, RC2, ACCESS
    BSF TRISC, RC6, ACCESS
    BSF TRISC, RC7, ACCESS
    CLRF LATC, ACCESS
    
    BSF RCON, IPEN, ACCESS	; ENABLE INTERRUPT PRIORITY
    BSF INTCON, GIEH, ACCESS	; ENABLE HIGH PRIO INTERRUPT
    BSF INTCON, GIEL, ACCESS	; ENABLE LOW PRIO INTERRUPT
    
    BSF INTCON2, INTEDG0, ACCESS    ; RECOG INT0 INTERRUPT IN RISING EDGE
    BCF INTCON, INT0IF, ACCESS	    ; CLEAR INT0 INTERRUPT FLAG
    BSF INTCON, INT0IE, ACCESS	    ; ENABLE INT0 INTERRUPT LINE
    
    BSF INTCON2, INTEDG1, ACCESS    ; RECOG INT1 INTERRUPT IN RISING EDGE
    BSF INTCON3, INT1IP, ACCESS	    ; SET INT1 AS HIGH PRIO
    BCF INTCON3, INT1IF, ACCESS	    ; CLEAR INT1 INTERRUPT FLAG
    BSF INTCON3, INT1IE, ACCESS	    ; ENABLE INT1 INTERRUPT LINE
    
    BSF INTCON2, TMR0IP, ACCESS	    ; SET TMR0 INTERRUPT AS HIGH
    BCF INTCON, TMR0IF, ACCESS	    ; CLEAR TMR0 INTERRUPT FLAG
    BSF INTCON, TMR0IE, ACCESS	    ; ENABLE TMR0 INTERRUPT LINE
    
    CLRF TMR0H, ACCESS
    CLRF TMR0L, ACCESS
    
    MOVLW 0x84 
    MOVWF T0CON, ACCESS	    ; ENABLE 16-BIT TMR0 1:32 PRES
    
    ;USART
    BCF PIR1, RCIF, ACCESS
    BSF IPR1, RCIP, ACCESS
    BSF PIE1, RCIE, ACCESS
    
    MOVLW 0x02
    MOVWF SPBRGH, ACCESS
    MOVLW 0x08
    MOVWF SPBRG, ACCESS
    ;BAUD RATE 9600
    MOVLW 0x08
    MOVWF BAUDCON, ACCESS
    
    MOVLW 0x24
    MOVWF TXSTA, ACCESS
    
    MOVLW 0x90
    MOVWF RCSTA, ACCESS
    
    CLRF MAIN_CTL, ACCESS
    CLRF R1, ACCESS
    
    ;GATE REGISTERS FOR COMPARISON
    MOVLW 0x04
    MOVWF REG_NOT, ACCESS
    MOVLW 0x08
    MOVWF REG_AND, ACCESS
    MOVLW 0x0C
    MOVWF REG_OR, ACCESS
    MOVLW 0x10
    MOVWF REG_NAND, ACCESS
    MOVLW 0x14
    MOVWF REG_XOR, ACCESS
    MOVLW 0x18
    MOVWF REG_NOR, ACCESS

MAIN:
    
;===================================IC SELECT===================================
;1111111111111111111111111111111111111=NOT=1111111111111111111111111111111111111
NOT_04_INIT:
    ;NOT GATE I/O INIT CONFIGS B and D
    MOVLW 0x6B
    MOVWF TRISB, ACCESS	; SET RB[0,1,3,5,6] as INPUT; RB[2,4,7] as OUT 
    
    
    MOVLW 0x2A
    MOVWF TRISD, ACCESS	; SET RD[1,3,5] as INPUT; RD[0,2,4] as OUT 
      
NOT_04:    
    BTFSC MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/CLR
    BRA AND_08_INIT			    ;JUMP to /NEXT/ IC_INIT
    
    BTFSC MAIN_CTL, 0x0, ACCESS	    ;FOR LOOP
    BRA NOT_04			    ;LOOP TO /SELF/
    
    MOVLW 0X04			    ;OUTPUT INDICATOR
    MOVWF LATA, ACCESS
    
    BTFSC MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/CLR
    BRA AND_08_INIT
    
    BCF MAIN_CTL, 0x1, ACCESS	    ;DISABLE CHANGE SEQ/ UNLESS INT1 IS PRESSED
    BSF MAIN_CTL, 0x0, ACCESS	    ;TO LOOP BACK
    BRA NOT_04			    ;LOOP TO /SELF/
;22222222222222222222222222222222222=AND=222222222222222222222222222222222222222
AND_08_INIT:
    ;AND GATE I/O INIT CONFIGS B and D
    MOVLW 0x53
    MOVWF TRISB, ACCESS	; SET RB[|0,1|,4,6] as INPUT; RB[2,3,5,7] as OUT 
    
    MOVLW 0x24
    MOVWF TRISD, ACCESS	; SET RD[2,5] as INPUT; RD[0,1,3,4] as OUT 

AND_08:
    
    BTFSS MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/SET
    BRA OR_32_INIT
    
    BTFSS MAIN_CTL, 0x0, ACCESS	    ;FOR LOOP
    BRA AND_08
    
    MOVLW 0X08
    MOVWF LATA, ACCESS
    
    BTFSS MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/SET
    BRA OR_32_INIT
    
    BSF MAIN_CTL, 0x1, ACCESS	    ;DISABLE CHANGE SEQ/ UNLESS INT1 IS PRESSED
    BCF MAIN_CTL, 0x0, ACCESS	    ;TO LOOP BACK
    BRA AND_08
;333333333333333333333333333333333333=OR=333333333333333333333333333333333333333
OR_32_INIT:
    MOVLW 0x53
    MOVWF TRISB, ACCESS	; SET RB[|0,1|,4,6] as INPUT; RB[2,3,5,7] as OUT 
    MOVLW 0x24
    MOVWF TRISD, ACCESS	; SET RD[2,5] as INPUT; RD[0,1,3,4] as OUT    
OR_32:
    BTFSC MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/CLR
    BRA NAND_00_INIT			    ;JUMP to /NEXT/ IC_INIT
    
    BTFSC MAIN_CTL, 0x0, ACCESS	    ;FOR LOOP
    BRA OR_32			    ;LOOP TO /SELF/
    
    MOVLW 0X0C			    ;OUTPUT INDICATOR
    MOVWF LATA, ACCESS
    
    BTFSC MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/CLR
    BRA NAND_00_INIT
    
    BCF MAIN_CTL, 0x1, ACCESS	    ;DISABLE CHANGE SEQ/ UNLESS INT1 IS PRESSED
    BSF MAIN_CTL, 0x0, ACCESS	    ;TO LOOP BACK
    BRA OR_32			    ;LOOP TO /SELF/
;44444444444444444444444444444444444=NAND=44444444444444444444444444444444444444
NAND_00_INIT:
    MOVLW 0x53
    MOVWF TRISB, ACCESS	; SET RB[|0,1|,4,6] as INPUT; RB[2,3,5,7] as OUT     
    MOVLW 0x24
    MOVWF TRISD, ACCESS	; SET RD[2,5] as INPUT; RD[0,1,3,4] as OUT 
NAND_00:
    BTFSS MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/SET
    BRA XOR_86_INIT
    
    BTFSS MAIN_CTL, 0x0, ACCESS	    ;FOR LOOP
    BRA NAND_00
    
    MOVLW 0X10
    MOVWF LATA, ACCESS
    
    BTFSS MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/SET
    BRA XOR_86_INIT
    
    BSF MAIN_CTL, 0x1, ACCESS	    ;DISABLE CHANGE SEQ/ UNLESS INT1 IS PRESSED
    BCF MAIN_CTL, 0x0, ACCESS	    ;TO LOOP BACK
    BRA NAND_00
;5555555555555555555555555555555555555=XOR=5555555555555555555555555555555555555
XOR_86_INIT:
    MOVLW 0x53
    MOVWF TRISB, ACCESS
    MOVLW 0x24
    MOVWF TRISD, ACCESS
XOR_86:
    BTFSC MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/CLR
    BRA NOR_02_INIT		    
    
    BTFSC MAIN_CTL, 0x0, ACCESS	    ;FOR LOOP
    BRA XOR_86			    ;LOOP TO /SELF/
    
    MOVLW 0X14			    
    MOVWF LATA, ACCESS
    
    BTFSC MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/CLR
    BRA NOR_02_INIT
    
    BCF MAIN_CTL, 0x1, ACCESS	    
    BSF MAIN_CTL, 0x0, ACCESS	    
    BRA XOR_86			    
;666666666666666666666666666666666=NOR=66666666666666666666666666666666666666666    
NOR_02_INIT:
    MOVLW 0x27
    MOVWF TRISB, ACCESS
    MOVLW 0x09
    MOVWF TRISD, ACCESS
NOR_02:
    BTFSS MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/SET
    BRA NOT_04_INIT
    
    BTFSS MAIN_CTL, 0x0, ACCESS	    ;FOR LOOP
    BRA NOR_02
    
    MOVLW 0X18
    MOVWF LATA, ACCESS
    
    BTFSS MAIN_CTL, 0x1, ACCESS	    ;FOR CHANGE SEQ/SET
    BRA NOT_04_INIT
    
    BSF MAIN_CTL, 0x1, ACCESS	    ;DISABLE CHANGE SEQ/ UNLESS INT1 IS PRESSED
    BCF MAIN_CTL, 0x0, ACCESS	    ;TO LOOP BACK
    BRA NOR_02
   
    
;==================================OUTPUT LEDS==================================    
GOOD_IC:
    ;BTFSC MAIN_CTL, 0x0, ACCESS
    ;BRA INT0_ISR_CONT
    
    BCF LATA, RA0, ACCESS
    BSF LATA, RA1, ACCESS
    
    ;BSF MAIN_CTL, 0x0, ACCESS
    BRA INT0_ISR_CONT
    
BAD_IC:
    ;BTFSC MAIN_CTL, 0x1, ACCESS
    ;BRA INT0_ISR_CONT
    
    BSF LATA, RA0, ACCESS
    BCF LATA, RA1, ACCESS
    
    ;BTFSC MAIN_CTL, 0x1, ACCESS
    BRA INT0_ISR_CONT ; BACK to INT0 ISR
;==============================GATE BIT SELECTOR================================
;	GATE SELECTOR through RC2, RC1, RC0
;			BITS = X    X	 X
;
CHK_BIT1:
    ;IF XX0
    BTFSC PORTC, RC0, ACCESS
    BRA CHK_BIT2
    BTFSC PORTC, RC1, ACCESS
    BRA CHK_BIT3_X10
    BTFSC PORTC, RC2, ACCESS
    BRA GATE_FOUR
    BRA UNMPLTD
    
    BRA CHK_BIT1
    
    
CHK_BIT2:
    ;IF XX1
    BTFSC PORTC, RC1, ACCESS
    BRA CHK_BIT3_X11
    BTFSC PORTC, RC2, ACCESS
    BRA GATE_FIVE
    BRA GATE_ONE
    
    BRA CHK_BIT2

CHK_BIT3_X10:
    ;IF X10
    BTFSC PORTC, RC2, ACCESS
    BRA GATE_SIX
    BRA GATE_TWO
    
    BRA CHK_BIT3_X10
    
CHK_BIT3_X11:
    ;IF X11
    BTFSC PORTC, RC2, ACCESS
    BRA UNMPLTD
    BRA GATE_THREE
    
    BRA CHK_BIT3_X11
;=================================GATE TESTER===================================
UNMPLTD:
    ; UNIMPLEMENTED 0 and 7 in GATE SELECTOR
    BSF LATA, RA0, ACCESS
    BSF LATA, RA1, ACCESS
    
    BRA INT0_ISR_CONT
;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^GATE ONE^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
GATE_ONE:
    ;TEST 1ST GATE via TRUTH TABLE (NOT)
    MOVF PORTA, W, ACCESS
    ANDLW 0x1C
    
    CPFSLT REG_NOT, ACCESS	    ;COMPARE GATE REGISTERS < WREG/PORTA
    BRA NOT_G1
    CPFSLT REG_AND, ACCESS
    BRA AND_G1
    CPFSLT REG_OR, ACCESS
    BRA OR_G1
    CPFSLT REG_NAND, ACCESS
    BRA NAND_G1
    CPFSLT REG_XOR, ACCESS
    BRA XOR_G1
    CPFSLT REG_NOR, ACCESS
    BRA NOR_G1
    
    BRA GATE_ONE
   
NOT_G1:
    ;GATE 1 TRUTH TABLE
    BSF LATB, RB2, ACCESS
    BTFSC PORTB, RB3, ACCESS
    BRA BAD_IC
    BCF LATB, RB2, ACCESS
    BTFSS PORTB, RB3, ACCESS
    BRA BAD_IC
    
    BRA GOOD_IC
    
    BRA NOT_G1
    
AND_G1:
    BCF LATB, RB2, ACCESS
    BCF LATB, RB3, ACCESS
    BTFSC PORTB, RB4, ACCESS
    BRA BAD_IC
    BCF LATB, RB2, ACCESS
    BSF LATB, RB3, ACCESS
    BTFSC PORTB, RB4, ACCESS
    BRA BAD_IC
    BSF LATB, RB2, ACCESS
    BCF LATB, RB3, ACCESS
    BTFSC PORTB, RB4, ACCESS
    BRA BAD_IC
    BSF LATB, RB2, ACCESS
    BSF LATB, RB3, ACCESS
    BTFSS PORTB, RB4, ACCESS
    BRA BAD_IC
    
    BRA GOOD_IC
    
    BRA AND_G1
    
OR_G1:
    BCF LATB, RB2, ACCESS
    BCF LATB, RB3, ACCESS
    BTFSC PORTB, RB4, ACCESS
    BRA BAD_IC
    BCF LATB, RB2, ACCESS
    BSF LATB, RB3, ACCESS
    BTFSS PORTB, RB4, ACCESS
    BRA BAD_IC
    BSF LATB, RB2, ACCESS
    BCF LATB, RB3, ACCESS
    BTFSS PORTB, RB4, ACCESS
    BRA BAD_IC
    BSF LATB, RB2, ACCESS
    BSF LATB, RB3, ACCESS
    BTFSS PORTB, RB4, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA OR_G1
    
NAND_G1:
    BCF LATB, RB2, ACCESS
    BCF LATB, RB3, ACCESS
    BTFSS PORTB, RB4, ACCESS
    BRA BAD_IC
    BCF LATB, RB2, ACCESS
    BSF LATB, RB3, ACCESS
    BTFSS PORTB, RB4, ACCESS
    BRA BAD_IC
    BSF LATB, RB2, ACCESS
    BCF LATB, RB3, ACCESS
    BTFSS PORTB, RB4, ACCESS
    BRA BAD_IC
    BSF LATB, RB2, ACCESS
    BSF LATB, RB3, ACCESS
    BTFSC PORTB, RB4, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA NAND_G1
 
XOR_G1:
    BCF LATB, RB2, ACCESS
    BCF LATB, RB3, ACCESS
    BTFSC PORTB, RB4, ACCESS
    BRA BAD_IC
    BCF LATB, RB2, ACCESS
    BSF LATB, RB3, ACCESS
    BTFSS PORTB, RB4, ACCESS
    BRA BAD_IC
    BSF LATB, RB2, ACCESS
    BCF LATB, RB3, ACCESS
    BTFSS PORTB, RB4, ACCESS
    BRA BAD_IC
    BSF LATB, RB2, ACCESS
    BSF LATB, RB3, ACCESS
    BTFSC PORTB, RB4, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA XOR_G1
    
NOR_G1:
    BCF LATB, RB3, ACCESS
    BCF LATB, RB4, ACCESS
    BTFSS PORTB, RB2, ACCESS
    BRA BAD_IC
    BCF LATB, RB3, ACCESS
    BSF LATB, RB4, ACCESS
    BTFSC PORTB, RB2, ACCESS
    BRA BAD_IC
    BSF LATB, RB3, ACCESS
    BCF LATB, RB4, ACCESS
    BTFSC PORTB, RB2, ACCESS
    BRA BAD_IC
    BSF LATB, RB3, ACCESS
    BSF LATB, RB4, ACCESS
    BTFSC PORTB, RB2, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA NOR_G1

;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^GATE TWO^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
GATE_TWO:
    ;TEST 2ND GATE
    MOVF PORTA, W, ACCESS
    ANDLW 0x1C
    
    CPFSLT REG_NOT, ACCESS	    ;COMPARE GATE REGISTERS < WREG/PORTA
    BRA NOT_G2
    CPFSLT REG_AND, ACCESS
    BRA AND_G2
    CPFSLT REG_OR, ACCESS
    BRA OR_G2
    CPFSLT REG_NAND, ACCESS
    BRA NAND_G2
    CPFSLT REG_XOR, ACCESS
    BRA XOR_G2
    CPFSLT REG_NOR, ACCESS
    BRA NOR_G2
    
    BRA GATE_TWO
   
NOT_G2:
    ;GATE 1 TRUTH TABLE
    BSF LATB, RB4, ACCESS
    BTFSC PORTB, RB5, ACCESS
    BRA BAD_IC
    BCF LATB, RB4, ACCESS
    BTFSS PORTB, RB5, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA NOT_G2
    
AND_G2:
    BCF LATB, RB5, ACCESS
    BCF LATB, RB7, ACCESS
    BTFSC PORTB, RB6, ACCESS
    BRA BAD_IC
    BCF LATB, RB5, ACCESS
    BSF LATB, RB7, ACCESS
    BTFSC PORTB, RB6, ACCESS
    BRA BAD_IC
    BSF LATB, RB5, ACCESS
    BCF LATB, RB7, ACCESS
    BTFSC PORTB, RB6, ACCESS
    BRA BAD_IC
    BSF LATB, RB5, ACCESS
    BSF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA AND_G2
    
OR_G2:
    BCF LATB, RB5, ACCESS
    BCF LATB, RB7, ACCESS
    BTFSC PORTB, RB6, ACCESS
    BRA BAD_IC
    BCF LATB, RB5, ACCESS
    BSF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    BSF LATB, RB5, ACCESS
    BCF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    BSF LATB, RB5, ACCESS
    BSF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA OR_G2
    
NAND_G2:
    BCF LATB, RB5, ACCESS
    BCF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    BCF LATB, RB5, ACCESS
    BSF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    BSF LATB, RB5, ACCESS
    BCF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    BSF LATB, RB5, ACCESS
    BSF LATB, RB7, ACCESS
    BTFSC PORTB, RB6, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA NAND_G2
 
XOR_G2:
    BCF LATB, RB5, ACCESS
    BCF LATB, RB7, ACCESS
    BTFSC PORTB, RB6, ACCESS
    BRA BAD_IC
    BCF LATB, RB5, ACCESS
    BSF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    BSF LATB, RB5, ACCESS
    BCF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    BSF LATB, RB5, ACCESS
    BSF LATB, RB7, ACCESS
    BTFSC PORTB, RB6, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA XOR_G2
    
NOR_G2:
    BCF LATB, RB7, ACCESS
    BCF LATB, RB6, ACCESS
    BTFSS PORTB, RB5, ACCESS
    BRA BAD_IC
    BCF LATB, RB7, ACCESS
    BSF LATB, RB6, ACCESS
    BTFSC PORTB, RB5, ACCESS
    BRA BAD_IC
    BSF LATB, RB7, ACCESS
    BCF LATB, RB6, ACCESS
    BTFSC PORTB, RB5, ACCESS
    BRA BAD_IC
    BSF LATB, RB7, ACCESS
    BSF LATB, RB6, ACCESS
    BTFSC PORTB, RB5, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA NOR_G2
;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^GATE THREE^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
GATE_THREE:
    ;TEST 3RD GATE
    MOVF PORTA, W, ACCESS
    ANDLW 0x1C
    
    CPFSLT REG_NOT, ACCESS	    ;COMPARE GATE REGISTERS < WREG/PORTA
    BRA NOT_G3
    CPFSLT REG_AND, ACCESS
    BRA AND_G3
    CPFSLT REG_OR, ACCESS
    BRA OR_G3
    CPFSLT REG_NAND, ACCESS
    BRA NAND_G3
    CPFSLT REG_XOR, ACCESS
    BRA XOR_G3
    CPFSLT REG_NOR, ACCESS
    BRA NOR_G3
    
    BRA GATE_THREE

NOT_G3:
    BSF LATB, RB7, ACCESS
    BTFSC PORTB, RB6, ACCESS
    BRA BAD_IC
    BCF LATB, RB7, ACCESS
    BTFSS PORTB, RB6, ACCESS
    BRA BAD_IC
    
    BRA GOOD_IC
    BRA NOT_G3
    
AND_G3:
    BCF LATD, RD0, ACCESS
    BCF LATD, RD1, ACCESS
    BTFSC PORTD, RD2, ACCESS
    BRA BAD_IC
    BCF LATD, RD0, ACCESS
    BSF LATD, RD1, ACCESS
    BTFSC PORTD, RD2, ACCESS
    BRA BAD_IC
    BSF LATD, RD0, ACCESS
    BCF LATD, RD1, ACCESS
    BTFSC PORTD, RD2, ACCESS
    BRA BAD_IC
    BSF LATD, RD0, ACCESS
    BSF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA AND_G3
    
OR_G3:
    BCF LATD, RD0, ACCESS
    BCF LATD, RD1, ACCESS
    BTFSC PORTD, RD2, ACCESS
    BRA BAD_IC
    BCF LATD, RD0, ACCESS
    BSF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BSF LATD, RD0, ACCESS
    BCF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BSF LATD, RD0, ACCESS
    BSF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA OR_G3
    
NAND_G3:
    BCF LATD, RD0, ACCESS
    BCF LATD, RD1, ACCESS
    BTFSC PORTD, RD2, ACCESS
    BRA BAD_IC
    BCF LATD, RD0, ACCESS
    BSF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BSF LATD, RD0, ACCESS
    BCF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BSF LATD, RD0, ACCESS
    BSF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA NAND_G3
 
XOR_G3:
    BCF LATD, RD0, ACCESS
    BCF LATD, RD1, ACCESS
    BTFSC PORTD, RD2, ACCESS
    BRA BAD_IC
    BCF LATD, RD0, ACCESS
    BSF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BSF LATD, RD0, ACCESS
    BCF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BSF LATD, RD0, ACCESS
    BSF LATD, RD1, ACCESS
    BTFSS PORTD, RD2, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA XOR_G3
    
NOR_G3:
    BCF LATD, RD1, ACCESS
    BCF LATD, RD2, ACCESS
    BTFSC PORTD, RD0, ACCESS
    BRA BAD_IC
    BCF LATD, RD1, ACCESS
    BSF LATD, RD2, ACCESS
    BTFSS PORTD, RD0, ACCESS
    BRA BAD_IC
    BSF LATD, RD1, ACCESS
    BCF LATD, RD2, ACCESS
    BTFSS PORTD, RD0, ACCESS
    BRA BAD_IC
    BSF LATD, RD1, ACCESS
    BSF LATD, RD2, ACCESS
    BTFSS PORTD, RD0, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    
    BRA NOR_G3
;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^GATE THREE^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
GATE_FOUR:
    ;TEST 4TH GATE
    MOVF PORTA, W, ACCESS
    ANDLW 0x1C
    
    CPFSLT REG_NOT, ACCESS	    ;COMPARE GATE REGISTERS < WREG/PORTA
    BRA NOT_G4
    CPFSLT REG_AND, ACCESS
    BRA AND_G4
    CPFSLT REG_OR, ACCESS
    BRA OR_G4
    CPFSLT REG_NAND, ACCESS
    BRA NAND_G4
    CPFSLT REG_XOR, ACCESS
    BRA XOR_G4
    CPFSLT REG_NOR, ACCESS
    BRA NOR_G4
    
    BRA GATE_FOUR
    
NOT_G4:
    
    BSF LATD, RD0, ACCESS
    BTFSC PORTD, RD1, ACCESS
    BRA BAD_IC
    BCF LATD, RD0, ACCESS
    BTFSS PORTD, RD1, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA NOT_G4
    
AND_G4:
    BCF LATD, RD3, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BCF LATD, RD3, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BSF LATD, RD3, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BSF LATD, RD3, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSS PORTD, RD5, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA AND_G4
    
OR_G4:
    BCF LATD, RD3, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BCF LATD, RD3, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BSF LATD, RD3, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BSF LATD, RD3, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSS PORTD, RD5, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA OR_G4
    
NAND_G4:
    BCF LATD, RD3, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BCF LATD, RD3, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BSF LATD, RD3, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BSF LATD, RD3, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSS PORTD, RD5, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA NAND_G4
 
XOR_G4:
    BCF LATD, RD3, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BCF LATD, RD3, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BSF LATD, RD3, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BSF LATD, RD3, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSS PORTD, RD5, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA XOR_G4
    
NOR_G4:
    BCF LATD, RD5, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD3, ACCESS
    BRA BAD_IC
    BCF LATD, RD5, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSC PORTD, RD3, ACCESS
    BRA BAD_IC
    BSF LATD, RD5, ACCESS
    BCF LATD, RD4, ACCESS
    BTFSC PORTD, RD3, ACCESS
    BRA BAD_IC
    BSF LATD, RD5, ACCESS
    BSF LATD, RD4, ACCESS
    BTFSS PORTD, RD3, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA NOR_G4
;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^GATE FIVE^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
GATE_FIVE:
    ;TEST 5TH GATE
    MOVF PORTA, W, ACCESS
    ANDLW 0x1C
    
    CPFSLT REG_NOT, ACCESS	    ;COMPARE GATE REGISTERS < WREG/PORTA
    BRA NOT_G5
    CPFSLT REG_AND, ACCESS	    ; UNIMPLEMENTED = 04:6 gates, others 4 gates
    BRA UNMPLTD	    
    CPFSLT REG_OR, ACCESS
    BRA UNMPLTD
    CPFSLT REG_NAND, ACCESS
    BRA UNMPLTD
    CPFSLT REG_XOR, ACCESS
    BRA UNMPLTD
    CPFSLT REG_NOR, ACCESS
    BRA UNMPLTD
    
    BRA GATE_FIVE
    
NOT_G5:
    BSF LATD, RD2, ACCESS
    BTFSC PORTD, RD3, ACCESS
    BRA BAD_IC
    BCF LATD, RD2, ACCESS
    BTFSS PORTD, RD3, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA NOT_G5
 ;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^GATE SIX^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
GATE_SIX:
    ;TEST 6TH GATE
    MOVF PORTA, W, ACCESS
    ANDLW 0x1C
    
    CPFSLT REG_NOT, ACCESS	    ;COMPARE GATE REGISTERS < WREG/PORTA
    BRA NOT_G5
    CPFSLT REG_AND, ACCESS	    ; UNIMPLEMENTED = 04:6 gates, others 4 gates
    BRA UNMPLTD	    
    CPFSLT REG_OR, ACCESS
    BRA UNMPLTD
    CPFSLT REG_NAND, ACCESS
    BRA UNMPLTD
    CPFSLT REG_XOR, ACCESS
    BRA UNMPLTD
    CPFSLT REG_NOR, ACCESS
    BRA UNMPLTD
    
    BRA GATE_SIX
    
NOT_G6:   
    BSF LATD, RD4, ACCESS
    BTFSC PORTD, RD5, ACCESS
    BRA BAD_IC
    BCF LATD, RD4, ACCESS
    BTFSS PORTD, RD5, ACCESS
    BRA BAD_IC
    BRA GOOD_IC
    BRA NOT_G6

;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^INTERRUPTS^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
; ALL HIGH PRIO INT
; INT0 = TEST/CHECK GATE
; INT1 = IC SELECTOR
HISR:
    ;High Prioity ISR
    BTFSC PIR1, RCIF, ACCESS
    RCALL RC_ISR
    BTFSC INTCON, INT0IF, ACCESS
    RCALL INT0_ISR
    BTFSC INTCON3, INT1IF, ACCESS
    RCALL INT1_ISR
    BTFSC INTCON, TMR0IF, ACCESS
    RCALL TMR0_ISR
    RETFIE FAST
;================================INTERRUPT0=====================================    
INT0_ISR:
    ;CHECK/TEST IC ISR
    BRA CHK_BIT1
    
    ;GATE SELECTOR++
    ;GATE CHECKER++
INT0_ISR_CONT:
    ;BACK from GATE CHECKER++
    ;BSF MAIN_CTL, 0x0, ACCESS
    BCF INTCON, INT0IF, ACCESS
    RETURN
;================================INTERRUPT1=====================================    
INT1_ISR:
    ; Button press ISR (with debouncing)
    MOVF DEBOUNCE_FLAG, W    ; Check if debounce is active
    BTFSC STATUS, Z          ; If DEBOUNCE_FLAG == 0, process the button press
    BRA DEBOUNCE_ACTIVE     ; Skip processing if debounce is active

    ; Handle button press
    BTG MAIN_CTL, 0x1, ACCESS ; Toggle the MAIN_CTL bit to change sequence
    BSF DEBOUNCE_FLAG, 0      ; Set debounce flag

    ; Start debounce timer
    MOVLW 0x00
    MOVWF TMR0H, ACCESS       ; Reset Timer0 high byte
    MOVLW 0x00
    MOVWF TMR0L, ACCESS       ; Reset Timer0 low byte
    BSF T0CON, TMR0ON, ACCESS ; Enable Timer0

    BCF INTCON3, INT1IF, ACCESS ; Clear INT0 interrupt flag
    RETURN

DEBOUNCE_ACTIVE:
    BCF INTCON3, INT1IF, ACCESS ; Clear INT0 interrupt flag
    RETURN
    
    
;==================================RECEIVE======================================
RC_ISR:
    BTFSC RCSTA, FERR, ACCESS
    BRA RC_ERR
    BTFSC RCSTA, OERR, ACCESS
    BRA RC_ERR
    
    MOVF RCREG, W, ACCESS
    ;MOVWF LATA, ACCESS
    
    ;BTFSC TXSTA, TRMT, ACCESS
    ;MOVWF TXREG, ACCESS
    
    RETURN
    
RC_ERR:
    BCF RCSTA, CREN, ACCESS
    BSF RCSTA, CREN, ACCESS
    RETURN

;==================================TIMER0=======================================    
TMR0_ISR:
    ;Delay ISR
    BCF INTCON, TMR0IF, ACCESS
    RETURN
    
    end